apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
  - image: fresh-catwalk-240714/springsvc
    jib: {}
  local: {}
deploy:
  kubectl: {}
# optional profile to run the jib build on Google Cloud Build
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}
