apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: service
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: service.sbadmin.192.168.64.30.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: service
          servicePort: 8085

