apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: springsvc
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: springsvc.jx.192.168.64.24.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: springsvc
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springsvc
spec:
  ports:
  - port: 8080
    name: http
  type: LoadBalancer
  selector:
    app: springsvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springsvc
spec:
  selector:
    matchLabels:
      app: springsvc
  template:
    metadata:
      labels:
        app: springsvc
    spec:
      containers:
      - name: springsvc
        image: gcr.io/fresh-catwalk-240714/springsvc
        ports:
          - containerPort: 8080
