apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: reactive-service
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: reactive-service.sbadmin.192.168.64.31.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: reactive-service
          servicePort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: reactive-service
spec:
  ports:
  - port: 8084
    name: http
  type: LoadBalancer
  selector:
    app: reactive-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactive-service
spec:
  selector:
    matchLabels:
      app: reactive-service
  template:
    metadata:
      labels:
        app: reactive-service
    spec:
      containers:
      - name: rest-service
        image: gcr.io/fresh-catwalk-240714/reactive-service:0.1.3-SNAPSHOT
        ports:
          - containerPort: 8084
        env:
          - name: SPRING_BOOT_URL
            value: ""
          - name: KUBERNETES_DISCOVERY
            value: "true"
          - name: SPRING_BOOT_ADMIN_CLIENT
            value: "false"
